### ISSUE TITLE
Is it possible to change opacity of content behind the image?

### ISSUE THREAD

**Issue by ccalvarez** [fengyuanchen/viewerjs#332]
I would like to change the opacity of content behind the image, I would like to make the content more visible:

![image](https://user-images.githubusercontent.com/2665104/67500053-591dab80-f63f-11e9-8727-58d1fb12a1f8.png)

Is it possible?  How can I set the value for opacity?

Thank you.

**Comment by fengyuanchen** [comment]
Just override the CSS styles:

```css
.viewer-backdrop {
  background-color: rgba(0, 0, 0, 0.8);
}
```
