### ISSUE TITLE
An option to make the navbar's thumbnails bigger

### ISSUE THREAD

**Issue by ataylor32** [fengyuanchen/viewerjs#353]
From what I've seen in the docs, there doesn't seem to be a way to make the navbar's thumbnails bigger. I'm working on a website that has many users who don't have great vision. It would be nice to double the size of the thumbnails. Is this doable?

**Comment by fengyuanchen** [comment]
You can override the navbar's style to enlarge the thumbnails.

**Comment by simplenotezy** [comment]
I'd like this as well!

It's seem rather complicated to override the navbar's style, as there is a fixed width/height on 3-4-5 elements.

**Comment by martinschilliger** [comment]
Just add for example 4x bigger values than default:
```css
.viewer-list {
  height: 200px;
}
.viewer-list > li {
  height: 200px;
  width: 120px;
}
```
