### ISSUE TITLE
当body高度设置为100%会出现滚动到头部的问题

### ISSUE THREAD

**Issue by loriwang** [fengyuanchen/viewerjs#454]
version: 1.9.0
如题,当把html设置为height:100%,overflow:auto;body的高度设置为100%的时候,每次打开弹窗都会出现滚动到头部的情况,在live的demo中进行了设置,打开chrome的preview,设置body的高度为100%,也会出现该情况,
如果给body 增加属性 overflow: auto 可以修复该问题,目前想如果不给body设置额外属性的时候,是否能修复该问题?

**Comment by fengyuanchen** [comment]
```css
body {
  box-sizing: border-box;
}
```
