### ISSUE TITLE
可以自定义toolbar的大小吗?

### ISSUE THREAD

**Issue by allen3371** [fengyuanchen/viewerjs#467]
这个组件非常好,解决了我很大的问题,
现在有个需求,就是这个toolbar的按钮有点小,能自定义按钮的尺寸吗?大一点看得清楚一些

谢谢!

**Comment by fengyuanchen** [comment]
You can override the CSS styles of the toolbar in your site directly.

```css
/* After imported the viewer.css */
.viewer-toolbar > ul > li {
  width: 48px;
  height: 48px;
}
```
