### ISSUE TITLE
Rotate thumbnails in navbar

### ISSUE THREAD

**Issue by mathias22osterhagen22** [fengyuanchen/viewerjs#503]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
Our Webapp is helping team members to rotate pages of documents in a good orientation.
For this, we are splitting the `PDF` document to multiple `JPG` files that are then displayed in `viewerjs`
  1. We are hooking the event `rotate` to save in our system the new orientation
  2. We overrode the `viewed` method to apply the page orientation if the user is going back on the page.

The issue is that the user needs to be on the page to see its actual rotation, we would love to apply rotation on the thumbnails as well: 
![image](https://user-images.githubusercontent.com/60438474/134705198-18e5f22f-5b88-4dd6-979f-4f066fc302ab.png)

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

I'm currently looking to make it looks like this: 
![image](https://user-images.githubusercontent.com/60438474/134705509-292e0b5b-e19d-4f0e-8916-1b523d0af498.png)

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
We thought about editing the DOM after a rotate event and as well after the `Viewer` initialization.
But we are running the web app on `Vue.js` and this would be really "dirty".

**Additional context**
_Add any other context or screenshots about the feature request here._
None.

**Comment by fengyuanchen** [comment]
Maybe you can try to add CSS styles to the thumbnails: `transform: rotate(90deg)`.

How to touch the thumbnails:

```js
new Viewer(image, {
  ready() {
    console.log(this.viewer.list.children);
  },
});
```

**Comment by mathias22osterhagen22** [comment]
Perfect @fengyuanchen! Exactly what I needed! Thank you a lot.

I managed by applying it like this: 
```js
//Assign CSS class based on current rotation
function  setClassBasedOnCurrentRotation (viewer) {
  viewer.list.children.forEach((navChild, index) => {
    [0,90,180,270].forEach(angle => navChild.classList.remove(`rotate-${angle}`));
    navChild.classList.add(`rotate-${this.file.orientation[index]}`); //vue.js this is the current instance
  });
},
//Transform angle to 0/90/180/270
function  normalizeAngle (angle) { 
 if (angle < 0) {
  if (Math.abs(angle) % 360 == 0) return 0;
  else return 360 - (Math.abs(angle) % 360);
 } else return Math.abs(angle) % 360;
},
  
let me = this; //let me this, keeping a pointer to "this" (instance of vue.js) 
new Viewer(image, {
  rotate(event) {
       let prevDegree = me.file.orientation[index];
       let degree = me.normalizeAngle(event.detail.degree);
       if (prevDegree != degree)
       {
           me.file.orientation[this.viewer.index] = degree;
           me.setClassBasedOnCurrentRotation(this.viewer);
       }
  },
  ready() {
    me.setClassBasedOnCurrentRotation(this.viewer);
  },
});
```

```css
.rotate-0 {
 -webkit-transform: rotate(0deg);
 -moz-transform: rotate(0deg);
 -ms-transform: rotate(0deg);
 -o-transform: rotate(0deg);
 transform: rotate(0deg);
}
.rotate-90 {
 -webkit-transform: rotate(90deg);
 -moz-transform: rotate(90deg);
 -ms-transform: rotate(90deg);
 -o-transform: rotate(90deg);
 transform: rotate(90deg);
}
.rotate-180 {
 -webkit-transform: rotate(180deg);
 -moz-transform: rotate(180deg);
 -ms-transform: rotate(180deg);
 -o-transform: rotate(180deg);
 transform: rotate(180deg);
}
.rotate-270 {
 -webkit-transform: rotate(270deg);
 -moz-transform: rotate(270deg);
 -ms-transform: rotate(270deg);
 -o-transform: rotate(270deg);
 transform: rotate(270deg);
}
``` 

**Note:**  Because I loaded the `.css` with an import directive in my `.vue` file `@import "~viewerjs/dist/viewer.css"` in a not `scoped` style tag. The `rotate-*` CSS classes are declared in a `style` element not `scoped` as well (else they do not applies).
