### ISSUE TITLE
Is there an alternate way to specify icons for toolbar items?

### ISSUE THREAD

**Issue by dodumosu** [fengyuanchen/viewerjs#576]
thank you for this excellent component! it's definitely the product of a great deal of hard work, and it's really useful.

**Is your feature request related to a problem? Please describe.**
I have three extra toolbar buttons, and the last (it seems to be a position thing, as changing the icons works for the previously defined buttons) doesn't render on Chrome-based browsers (I've tried Chromium and Edge): 
![msedge_nZZeHqXrA2](https://user-images.githubusercontent.com/1408662/205334595-17132932-250b-49fe-8f7f-c0de6feb0c7d.png)

but does on Firefox:
![firefox_kFFC1pgO3o](https://user-images.githubusercontent.com/1408662/205334770-cb235aeb-c607-4deb-904c-1f5f820ba920.png)

this is the CSS for the toolbar buttons:

```css
  .viewer-download, .viewer-delete, .viewer-close {
    color: #fff;
    font-family: FontAwesome, serif;
    font-size: 0.75rem;
    line-height: 1.5rem;
    text-align: center;
  }

  .viewer-close::before {
    content: "\f00d";
  }

  .viewer-delete::before {
    content: "\f1f8";
  }

  .viewer-download::before {
    content: "\f019";
  }
```

this is the configuration for the `toolbar` option of the viewer:

```js
      toolbar: {
        zoomIn: true,
        zoomOut: true,
        reset: true,
        oneToOne: true,
        play: false,
        prev: true,
        next: true,
        rotateLeft: true,
        rotateRight: true,
        flipHorizontal: true,
        flipVertical: true,
        download: function() {
          /* code goes here */
        },
        delete: function() {
          /* code goes here */
        },
        close: function() {
          /* code goes here */
        }
      }
```

from the above, the close button icon doesn't display on Chrome

**Describe the solution you'd like**
The extra toolbar icons should all display correctly.

**Additional context**
When all three icons are changed to the FontAwesome close icon `\f2d4`:
![Code_QHF29uyN0M](https://user-images.githubusercontent.com/1408662/205337217-6ca16bf0-48eb-4e80-b069-8445df1e125b.png)

here's how it renders on Chrome:
![msedge_hjX0wYpwUQ](https://user-images.githubusercontent.com/1408662/205337272-fd52a93c-5881-42e9-8f10-3952bb7bcb73.png)
